POST  http://localhost:3000/user/register
Content-Type:application/json

{
   "username": "Rodri@badass.cool",
   "password": "123456Az"
}

###

POST http://localhost:3000/user/login
Content-Type:application/json

{
   "username": "Rodri@badass.cool",
   "password": "123456Az"
}

###

GET http://localhost:3000/user/logout/5dd2b72d71b003780b14b983

{
   "username": "Rodri@badass.cool",
   "token" : "3e5d4c9e-953d-4cfe-a75b-f135f44d65a2",
}

###

GET  http://localhost:3000/user/5dd55f7fb0e22c230088a8fe
Content-Type:application/json

{
   "username": "Rodri@badass.cool",
   "password": "123456Az"
}
###

GET  http://localhost:3000/movies/
Content-Type:application/json
